@startuml

component "NetworkInterface" as NI {

  interface "NetworkInterface" as NII {
    + generateUniqueId()
    + registerSubscriber(unsigned int subscriberId, unsigned int topicId)
    + setupServer(unsigned int componentId, Observer&)
  }

  class "LocalLinuxInterface" as LLI {

  }

}

LLI -u-|> NII : "implements"



@enduml

`
