@startuml

node "Services" {
  [Remote Access Gateway] as RAG
  [Remote Data Inlat]     as RDI
  [Drive Status Reporter] as DSR
  [Drive Controller]      as DC
  [Drive Operator]        as DO
  [Remote Data Outlet]    as RDO

  HTTP - RAG
}

node "MiddleWare" {
  [Message Broker] as MB

  "TCP/UART" -down- MB
}

node "Infrastructure" {
  [Hardware Interface] as HI
}

RAG -down-> "TCP/UART"
RDI -down-> "TCP/UART"
DSR -down-> "TCP/UART"
DC  -down-> "TCP/UART"
DO  -down-> "TCP/UART"
RDO -down-> "TCP/UART"

DO -right-> HI

@enduml
