@startuml
skinparam linetype polyline

actor "End User" as EU

frame TheRobot {
  frame ServiceLayer {
    component "Main" as M
    component "Service Builder" as SB
    component "Remote Access Gateway" as RAG
    component "Remote Data Entrance" as RDEN
    component "Drive Status Reporter" as DSR
    component "Drive State Controller" as DSC
    component "Remote Data Exit" as RDEX
  }
  
  frame HardwareLayer {
    component "General Purpose Input Output" as GPIO
    component "Pulse Width Modulation" as PWM
    component "Universal Asynchronous Receive Transmit" as UART
    component "I2C" as I2C
  }
}

EU <<-down->> RAG

''' Intra ServiceLayer
M .left.>> SB

RAG  .up.>> M
RAG  .up.>> SB
RDEN .up.>> M
RDEN .up.>> SB
DSR  .up.>> M
DSR  .up.>> SB
DSC  .up.>> M
DSC  .up.>> SB
RDEX .up.>> M
RDEX .up.>> SB

''' ServiceLayer to HardwareLayer
RAG .down.>> UART
DSR .down.>> I2C
DSC .down.>> PWM

@enduml
