@startuml

node "Services" {
  [Remote Access Gateway] as RAG
  [Remote Data Entrance]     as RDE
  [Drive Status Reporter] as DSR
  [Drive Controller]      as DC
  [Drive Operator]        as DO
  [Remote Data Exit]    as RDE
}

node "MiddleWare" {
  [Messaging] as MSG
}

node "Infrastructure" {
  [Hardware Interface] as HI
}

RAG .down.> MSG
RDE .down.> MSG
DSR .down.> MSG
DC  .down.> MSG
DO  .down.> MSG
RDE .down.> MSG

RAG .down.> HI
DSR .down.> HI
DO .down.> HI


@enduml
