@startuml

interface ServiceFactory as SF

interface Service as S

interface Observer<DriveStateCommand> as ODC

interface Observer<DriveStatus> as ODS

component DriveStateMaintainer {
 
  class DriveStateMaintainerFactory as DSMF
  {
  }

  class Main as M
  {
  }

  class CommandWatcher as CW
  {
    + getCommand() : const DriveStateCommand&  
  }

  class StatusWatcher as SW
  {
    + getStatus() : const DriveStatus& 
  }

  class DriveStateController
  {
    + setDriveState(const DriveStateCommand& command
  }
}

DSMF -u-|> SF
M -u-|> S
M *-u-> "1" CW
M *-u-> "1" SW
M *-u-> "1" C
CW -u-|> ODC
SW -u-|> ODS


@enduml
