@startuml

interface "Service" as S
interface "ServiceFactory" as SF

component Main {
  class "ServiceHeadQuarters" as SHQ
  {
    + initializeServices() : void
    + getServiceList() : ArrayList<Service*> 
  }

  interface "ServiceScheduler" as SS
  {
    + initializeShedule(ArrayList<Service*> services) : void
    + runSchedule() : void
  }

  class "FIFOScheduler" as FS  
  
  class "Main" as M
  {
    + main()
  }
}

M *-u-> "1" SHQ
M o-u-> "1" SS
FS -u-|> SS

SHQ o-u-> "1" SF
SHQ o-u-> "*" S

SS .u.> S

@enduml
