@startuml


actor       "remote client"                            as rc
participant "Remote Access Gateway"                    as RAG
participant "External Data Translator"                 as EDT
participant "Message Broker"                           as MB
participant "Drive Controller"                         as DC

rc -> RAG : "bytes representing drive control message"
RAG -> EDT : translate("bytes representing drive control message")

alt "translation successful"

  EDT --> RAG : "drive control message"
  RAG --> rc : "command accepted"

  RAG -> MB : publish("drive control topic", "drive control message")
  MB -> DC : consume("drive control topic")
  DC -> DC : set "drive control message"

else 

  RAG --> rc : "command rejected"  

end





@enduml

