@startuml

start

repeat
:Remote Access Gateway
  * Handle accepting or rejecting of connection requests
  * Produces ConnectionStatus to MessageBroker
  * Receives data from connected client
  * Produces RemoteInboundData to MessageBroker
  * Consumes RemoteOutboundData from MessageBroker
  * Transmits data from RemoteOutboundData to connected client; 

:Remote Data Entrance
  * Consumes RemoteInboundData from MessageBroker
  * Translates RemoteInboundData
  * Produces translated message to MessageBroker;

:Drive Status Reporter
  * Receives signals from drive system hardware
  * Translates signals from hardware to DriveStateStatus messages
  * Produces DriveStateStatus to MessageBroker;

:Drive State Controller
  * Consumes DriveStateCommand from MessageBroker
  * Consumes DriveStatus from MessageBroker
  * Generates DriveControlCommand using control algorithm
  * Produces DriveControlCommand to MessageBroker;

:Remote Data Exit
  * Consumes target messages from MessageBroker
  * Translates target messages to RemoteOutboundData messages
  * Produces RemoteOutboundData messages to MessageBroker;

repeat while (Shutdown?) is (No) not (Yes)

end

@enduml

