# Set base image
FROM archlinux:latest 

# Update packages and get sudo
RUN pacman -Syu --noconfirm sudo

# Create user space 
ARG username=development-user 
ARG password=UnsecurePassword
RUN useradd -m $username
RUN yes $password | passwd $username

# Add user to sudoers
RUN echo "$username ALL=(ALL:ALL) ALL" >> /etc/sudoers

# Do subsequent commands as the env-user
USER $username
WORKDIR /home/$username

# Update packages and get dependencies
RUN echo $password | sudo -S pacman -S --noconfirm gcc git neovim

# Add the nvim config directory to container so nvim can use it
ADD neovim-config/ .config/nvim/
RUN echo $password | sudo -S chown -R $username .config/

# Set the entrypoint for when this container is run
ENTRYPOINT nvim
